Repository RummelBumsDevelopment/Puhmuckl, pull requests merged in 2022-02, with the labels that each got.

#6 Fixed bugs in config script
  puhmuckl/bot.py
  puhmuckl/util/config.py
Labels: bug

#7 Changed project structure
  puhmuckl/bot.py
  puhmuckl/cogs/echo/__init__.py
  puhmuckl/cogs/echo/echo.py
Labels: enhancement

#9 fixed log level config
  puhmuckl/bot.py
Labels: bug

#11 replaced discord.py with py-cord
  requirements.txt
Labels: enhancement

#12 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#14 updated aiohttp version
  requirements.txt
Labels: bug

#18 added version presence
  .gitignore
  puhmuckl/bot.py
Labels: enhancement

#25 Create pylint.yml
  .github/workflows/pylint.yml
  README.md
Labels: enhancement

#27 Fixed pylint errors
  .github/workflows/pylint.yml
  puhmuckl/bot.py
  puhmuckl/cogs/echo/__init__.py
  puhmuckl/cogs/echo/echo.py
  puhmuckl/util/config.py
  puhmuckl/util/relative.py
  requirements.txt
Labels: enhancement

#23 Update README.md
  README.md
Labels: good first issue

#31 no nazimod
  puhmuckl/cogs/ingmar/ingmar.py
Labels: bug

#8 Added Wolfram|Alpha cog
  puhmuckl/cogs/wolframalpha/__init__.py
  puhmuckl/cogs/wolframalpha/wolframalpha.py
  puhmuckl/cogs/wolframalpha/wolframapi.py
  puhmuckl/util/interactive.py
  requirements.txt
Labels: enhancement

#41 Wolfram fix
  .gitignore
  puhmuckl/cogs/wolframalpha/wolframalpha.py
  puhmuckl/cogs/wolframalpha/wolframapi.py
Labels: bug
